# a simple debian 
# FROM registry.atlas.b2w:5000/atlas/debian-plataforma:jessie
FROM nginx
COPY viewer /usr/share/nginx/html

# NGINX as the application server
# RUN wget http://nginx.org/packages/ubuntu/xenial nginx
# RUN deb http://nginx.org/packages/debian/ jessie nginx
# ADD ../config/nginx.conf /etc/nginx/sites-available/default
# RUN service nginx restart 

# simulador-bf install
# RUN mkdir /opt/simulador-bf
# ADD add ../dist/simulador-bf.tar.gz /tmp
# RUN tar -xzf /tmp/simulador-bf.tar.gz -C /opt/simulador-bf

